### PR TITLE
Added functionality for high and low tax types

### PR DESCRIPTION
**Pull request by SebastiaanKloos**
In the Netherlands we have more than one tax rate. 

High: 21% and Low: 6%.

https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/internationaal/btw_voor_buitenlandse_ondernemers/btw_berekenen/btw_tarieven/

I've added this functionality to this repository to help Dutch users.

### CODE REVIEW

**Comment by mpociot** [comment]
Thank you! Can you add a test for this too?

**Comment by SebastiaanKloos** [comment]
@mpociot I'll try to add a test to it!

**Comment by SebastiaanKloos** [comment]
I've added some tests.

**Comment by SebastiaanKloos** [comment]
@mpociot Can you please review my code and merge if accepted?

**Comment by mxmtsk** [comment]
I was just about to open an issue for this. Any updates on when this will be merged? Germany also has two tax types, 19% and 7%

**Comment by SebastiaanKloos** [comment]
@mxmtsk no response yet from moderators

**Comment by mxmtsk** [comment]
@mpociot Any thoughts on this, it's been a while? :)
@SebastiaanKloos would you  consider adding another checkin to make it more complete and reflect Germany also?

```php
            'rate'   => 0.19,
            'rates' => [
                'high' => 0.19,
                'low' => 0.07,
            ],
```

**Pull request merged**
