### PR TITLE
Swap IP to Country API

### PR DESCRIPTION
**Pull request by Fossil01**
Swapped to it supports IPv6.

### CODE REVIEW

**Comment by mpociot** [comment]
Thank you for this PR. I can't see where this changes the actual GeoIP lookup. Did you forget that part?

**Comment by Fossil01** [comment]
Bloody Travis wont accept it for some reason. Anyway, you are right lol. I deleted the PR and then added it again, forgot to add the URL :-)

Fixed now.

**Comment by Fossil01** [comment]
Another way to go about this would be to use something like this https://github.com/Torann/laravel-geoip with the free MaxMind Lite database.

**Comment by Fossil01** [comment]
For those still having this issue. My fork uses another API. Might put in some work to make it use a local IP database so no external calls are necessary.

https://github.com/Fossil01/vat-calculator

**Comment by dainemedia** [comment]
Any progress on fixing this issue at all? At present, we can't use the getIPBasedCountry method, as this results in a 500 internal server error when the client's IP is IPv6.

**Comment by Fossil01** [comment]
Closing. I recommend switching to https://github.com/spaze/vat-calculator

**Comment by driesvints** [comment]
Heya, I'm gonna re-open this to have a look soon I hope. Thanks!

**Comment by Fossil01** [comment]
@driesvints It might be better to go the way @spaze went and rip out the Country to IP stuff and make people use whatever they need/want.

**Comment by driesvints** [comment]
Thanks, I've merged this PR on master.

**Comment by driesvints** [comment]
Btw, I'm still open to changing that. Feel free to PR if you like 👍

**Pull request closed without merging**
