### PR TITLE
Update .vat-taxrate with the current VAT percentage

### PR DESCRIPTION
**Pull request by orottier**

### CODE REVIEW

**Comment by mpociot** [comment]
Hey,

can you please update the README containing the JS extra fields too?

https://github.com/mpociot/vat-calculator#extra-fields

Thank you.

**Comment by orottier** [comment]
Hey there, forgot about that. I've added it!
Thanks

**Comment by mpociot** [comment]
Great. Thank you for the PR :)

**Comment by orottier** [comment]
Thank you for this very useful repo!

**Pull request merged**
